#!/bin/sh /etc/rc.common
# Copyright (C) 2016 EasyPi Software Foundation

START=99
USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /usr/bin/ssh -y -N -K 60 \
                                             -R 2222:127.0.0.1:22 \
                                             -i /etc/dropbear/dropbear_rsa_host_key \
                                             root@1.2.3.4
        procd_set_param respawn 3600 5 0
        procd_close_instance
}
